### ISSUE TITLE
CSI lInux - Powerup command issue

### ISSUE THREAD

**Issue by Subashtech14** [CSILinux/CSILinux-Powerup#1]
csi linux on power up it takes up to 4 hours in downloading the zip file,
I Have 100Mbps high speed network but the download is too slow please check on the sever side

**Comment by infosecwriter** [comment]
What version of CSI linux do you have?

**Comment by infosecwriter** [comment]
I've tested it from my side and I had a 41mb download speed.  The zip was pulled in less than a minute.  

Make sure /opt/csitools/powerup contains this:

_wget https://raw.githubusercontent.com/CSILinux/CSILinux-Powerup/main/csitoolsupdate22.sh -O - | sh | tee /home/csi/powerup.log_

This is updated when you run powerup if the image is older than a few months old, but this should kick start to ensure everything is pointed to new locations.

**Comment by infosecwriter** [comment]
I've tested it from my side and I had a 41mb download speed. The zip was pulled in less than a minute.

Make sure /opt/csitools/powerup contains this:

wget https://raw.githubusercontent.com/CSILinux/CSILinux-Powerup/main/csitoolsupdate22.sh -O - | sh | tee /home/csi/powerup.log

This is updated when you run powerup if the image is older than a few months old, but this should kick start to ensure everything is pointed to new locations.

**Comment by Subashtech14** [comment]
Thanks it now works fine bro
