### ISSUE TITLE
csitools.7z: URL not found

### ISSUE THREAD

**Issue by tsvietOK** [CSILinux/CSILinux-Powerup#4]
When powerup trying to download file [csitools.7z](https://csilinux.com/downloads/csitools.7z) it shows an error, file also unavailable in browser:
![image](https://github.com/user-attachments/assets/6d9b9028-c440-4c12-bdcb-4b41dae21417)

**Comment by tgeek77** [comment]
Confirmed. I'm seeing this also.

**Comment by tsvietOK** [comment]
It works now.
